### PR TITLE
Initial knxctl attempt

### PR DESCRIPTION
**Pull request by Fale**
Add a simple command line interface to knx-go.

This PR wants to mostly understand if there is the appetite for this kind of feature :).

### CODE REVIEW

**Comment by vapourismo** [comment]
In general I think it makes sense to have a tool like this in the repository. However, given I don't actively maintain this package apart from reviewing the occasional DPT PR, I don't think it is a good idea to have me become the blocker when facilitating PRs to this tool.

**Comment by Fale** [comment]
Thanks for the reply :).
How would you see migrating this repo to a dedicated GitHub org so that it would be easier to have a group of people managing it?

**Comment by vapourismo** [comment]
If there is a fork with momentum which looks generally sensible to me, I would not mind linking to it from this repository.

**Comment by Fale** [comment]
Makes sense, thanks :)

**Pull request closed without merging**
