### PR TITLE
Added DPT 1.100 (Heat/Cool)

### PR DESCRIPTION
**Pull request by cespedes**
Adding DPT 1.100, used in some climate equipment

### CODE REVIEW

**Review by vapourismo — DISMISSED** [review]

**Comment by cespedes** [comment]
Hi, Ole.
Do you know when will this PR be merged?

**Comment by vapourismo** [comment]
Not sure why, but there is still one loose CI action pending that hasn't passed. Can you please amend the top commit and force push to retrigger?

**Comment by cespedes** [comment]
Ok, I already amended the commit and did a force push.  Waiting for your approval...

**Review by vapourismo — APPROVED** [review]

**Comment by vapourismo** [comment]
Ok, something is clearly off with CI. I am going to have a look at this tomorrow. Apologies about the delay.

**Pull request merged**
