### PR TITLE
 Add  support for 7.XXX DPT type

### PR DESCRIPTION
**Pull request by alexander-zimmermann**

### CODE REVIEW

**Review by vapourismo — CHANGES_REQUESTED** [review]
Thanks for the contribution :heart: 
I think this only needs a run through `go fmt` and then it is good to go.

**Comment by vapourismo** [comment]
I am not sure why GitHub displays it like this, but this PR is actually merged. Just an FYI.

**Comment by alexander-zimmermann** [comment]
Thanks!

I'm going to add a couple of DPTs more in the next days.

Alex

**Comment by vapourismo** [comment]
Amazing!

**Pull request closed without merging**
